name: Create Blog Post PR

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Blog post title'
        required: true
        type: string
      category:
        description: 'Blog post category'
        required: false
        default: 'Technology'
        type: string
      tags:
        description: 'Tags (comma-separated)'
        required: false
        default: 'blog'
        type: string
      description:
        description: 'SEO description'
        required: false
        type: string

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate blog post filename
        id: filename
        run: |
          # Convert title to filename format
          FILENAME=$(echo "${{ github.event.inputs.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
          echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
          echo "filepath=content/posts/${FILENAME}.md" >> $GITHUB_OUTPUT

      - name: Create blog post file
        run: |
          mkdir -p content/posts
          CURRENT_DATE=$(date +%Y-%m-%d)
          cat > "${{ steps.filename.outputs.filepath }}" << EOF
          ---
          title: "${{ github.event.inputs.title }}"
          date: "$CURRENT_DATE"
          author: "Franco"
          category: "${{ github.event.inputs.category }}"
          tags: ["${{ github.event.inputs.tags || 'blog' }}"]
          featured: false
          published: true
          description: "${{ github.event.inputs.description || 'New blog post' }}"
          keywords: ["${{ github.event.inputs.tags || 'blog' }}"]
          ---

          # ${{ github.event.inputs.title }}

          Write your blog post content here...

          ## Introduction

          Add your introduction here.

          ## Main Content

          Add your main content here.

          ## Conclusion

          Add your conclusion here.
          EOF

      - name: Process markdown to JSON
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new blog post: ${{ github.event.inputs.title }}"
          title: "New Blog Post: ${{ github.event.inputs.title }}"
          body: |
            ## New Blog Post

            **Title:** ${{ github.event.inputs.title }}
            **Category:** ${{ github.event.inputs.category }}
            **Tags:** ${{ github.event.inputs.tags }}

            ### Files Modified:
            - `${{ steps.filename.outputs.filepath }}` - New blog post markdown
            - `source/blog/data/posts.json` - Updated post index
            - `source/blog/data/posts/${{ steps.filename.outputs.filename }}.json` - Generated post data

            ### Next Steps:
            1. Edit the blog post content in `${{ steps.filename.outputs.filepath }}`
            2. Review and approve this PR
            3. Merge to automatically deploy to the website

            ---
            🤖 This PR was automatically created by the Create Blog Post workflow.
          branch: blog-post/${{ steps.filename.outputs.filename }}
          delete-branch: true